version: "3.8"

services:
  app:
    build: .
    container_name: app
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - ./src:/app/src
    links:
      - db

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redeems
      MYSQL_USER: redeems
      MYSQL_PASSWORD: redeems
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 
    logging:
      driver: none


volumes:
  db_data: {}